version: '3'

services:
  web:
    build: .
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
